baseurl: /stackars-koalorna
repository: limbero/stackars-koalorna
collections:
  koalor:
    title: "Om koalor"
    order: 2
    output: true
  omoss:
    title: "Om oss"
    order: 1
    output: true
  slutsats:
    title: "Slutsats"
    order: 5
    output: true
  historia:
    title: "Historia"
    order: 3
    output: true
  problem:
    title: "Problem och konsekvenser"
    order: 4
    output: true
  atgarder:
    title: "Åtgärder"
    order: 6
    output: true
  kallor:
    title: "Källor"
    order: 7
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
